const SHOPS = [
  { url: 'https://js-yah.wieggers.eu', naam: 'Yaaqoub Alatrash' },
  { url: 'https://js-rgn.wieggers.eu', naam: 'Ruud Geelen' },
  { url: 'https://js-mgb.wieggers.eu', naam: 'Moustafa Gharib' },
  { url: 'https://js-nha.wieggers.eu', naam: 'Niels Hoekzema' },
  { url: 'https://js-jkf.wieggers.eu', naam: 'Jarne Kampshof' },
  { url: 'https://js-jlr.wieggers.eu', naam: 'Justin de Lepper' },
  { url: 'https://js-rmn.wieggers.eu', naam: 'Robin Miljoen' },
  { url: 'https://js-dpk.wieggers.eu', naam: 'Dominik Pieczak' },
  { url: 'https://js-gbn.wieggers.eu', naam: 'Gianluca Bergen' },
  { url: 'https://js-js-web02.wieggers.eu', naam: 'Martijn van Boven' },
  { url: 'https://js-lbk.wieggers.eu', naam: 'Lucas Bussink' },
  { url: 'https://js-jcz.wieggers.eu', naam: 'Jelle Christenhusz' },
  { url: 'https://js-mgk.wieggers.eu', naam: 'Mara Gesink' },
  { url: 'https://js-tgs.wieggers.eu', naam: 'Timo Geurts' },
  { url: 'https://js-dge.wieggers.eu', naam: 'Denizel Gökçe' },
  { url: 'https://js-mgf.wieggers.eu', naam: 'Marvin de Graaf' },
  { url: 'https://js-jhs.wieggers.eu', naam: 'Jayvano Hendriks' },
  { url: 'https://js-hie.wieggers.eu', naam: 'Hadi Idle' },
  { url: 'https://js-bkk.wieggers.eu', naam: 'Burak Koçak' },
  { url: 'https://js-jkk.wieggers.eu', naam: 'Jochem Kok' },
  { url: 'https://js-dmd.wieggers.eu', naam: 'Daud Mahamud' },
  { url: 'https://js-krn.wieggers.eu', naam: 'Keano van Rheenen' },
  { url: 'https://js-dws.wieggers.eu', naam: 'Daan Weggemans' },
  { url: 'https://js-fwg.wieggers.eu', naam: 'Frits Welsing' },
  { url: 'https://js-zjw.wieggers.eu', naam: 'Zhen-Jelte Wolsink' },
];
