FROM nginx:alpine
COPY nginx.conf        /etc/nginx/conf.d/default.conf
COPY index.html        /usr/share/nginx/html/index.html
COPY config.js         /usr/share/nginx/html/config.js
COPY weekend_score.png /usr/share/nginx/html/weekend_score.png
